# Generated by Django 4.1.6 on 2023-03-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.AddField(
            model_name='person',
            name='ofscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='onscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='tscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
