# Generated by Django 4.1.6 on 2023-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='player',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='txt',
            new_name='value',
        ),
    ]
