# Generated by Django 4.1.6 on 2023-03-16 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0002_room_delete_chat_rename_player_message_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1000)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamepage.room')),
            ],
        ),
    ]
